version: "3.9"

services:
    php:
        container_name: "app-php"
        build:
            context: ./php
        volumes:
            - ${APP_FOLDER}:/var/www
            - ${PHP_CONF_FILE}:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - database
    webserver:
        container_name: "app-webserver"
        build:
            context: ./nginx
        volumes:
            - ${APP_FOLDER}:/var/www
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ${WEB_LOG_FOLDER}:/var/log
        depends_on:
            - php
        ports:
            - "80:80"
    database:
        container_name: "app-database"
        build:
            context: ./mariadb
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"